### ISSUE TITLE
ruby parser

### ISSUE THREAD

**Issue by kennethgeerts** [jwadhams/json-logic-js#14]
Not sure whether this is the correct place to signal this, but I don't really find an alternative channel:

I've wrote a ruby parser for **json-logic**, it's located [here](https://github.com/kennethgeerts/json-logic-ruby). I'll be releasing a first version of the gem somewhere this week.
Just wanted to point out that I'm very happy to accept PR's and open to suggestions.

Thanks!

**Comment by jwadhams** [comment]
Oh, wow, that's fantastic!  Ping me when you're ready and I'll add a link in the right column of jsonlogic.com !

**Comment by kennethgeerts** [comment]
I've got all tests passing and released a fist version on RubyGems. A link to the ruby parser would be cool!

**Comment by szimmer1** [comment]
Late to the party, but here's [my version](https://github.com/szimmer1/jlr). Only difference here is my version compiles the rules to a decision/goal tree first. Intention is (in future commits) to prune unnecessary branches and do operations on primitives at compile time in order to reduce runtime. Thanks for a nice spec!
