### ISSUE TITLE
securing "method" operator 

### ISSUE THREAD

**Issue by sebastienmegnin** [jwadhams/json-logic-js#31]
Hi,
We are currently using jsonLogic as a rule engine where our customers can inject data and rules.
The method operator creates a security issue as we can not avoid side effects on our back end if java script code is injected.
is it possible to secure this feature ?

regards
Sebastien

**Comment by jwadhams** [comment]
Well, one option might be to add a feature like:

```js
  jsonLogic.rm_operation = function(name) {
    delete operations[name];
  };
```

Then as you're setting up you can turn off `method`, like:

```js
jsonLogic.apply({"method":[{"var":"c"}, "log", ["BEEP"]]}, {"c":console})
// BEEP

jsonLogic.rm_operation('method')

jsonLogic.apply({"method":[{"var":"c"}, "log", ["BEEP"]]}, {"c":console})
//Error: Unrecognized operation method
```

There might be a more elegant fix if you could walk me through a specific exploit. How are customers injecting data? If they're passing JSON you unpack yourself, I'm not sure how they can get a reference to outside functions. The example above works because the data is raw JavaScript, but this fails:

```js
var rule = JSON.parse('{"method":[{"var":"c"}, "log", ["BEEP"]]}');

var data = JSON.parse('{"c":console}');
//SyntaxError: Unexpected token c in JSON at position 5

jsonLogic.apply(rule, data);
//TypeError: Cannot read property 'log' of null
```

It will let you call methods on primitives, but I can't think of one that's dangerous:

```js
var rule = JSON.parse('{"method":[{"var":"clue"}, "toUpperCase"]}');

var data = JSON.parse('{"clue":"I\'m not shouting"}');

jsonLogic.apply(rule, data);
//"I'M NOT SHOUTING"
```

(That could of course be a lack of imagination on my part, and there's no telling what someone has monkey patched into some primitive's prototype, I suppose.)

**Comment by sebastienmegnin** [comment]
Thks !
We have to study deeper potential security threats. 
JsonLogic is our choice because of its secured and controlled execution model.
There s no problem removing `"method"` operation.
One operator we added is a `get` in a key/value store in order to make rules context aware : example external temperature, ...
This context is set with REST APIs

Regards

**Comment by jwadhams** [comment]
The new `rm_operation` method is now shipping in 1.1.3!

Sounds like you have a really cool use case. Is any of it public that I could look at?

**Comment by asanglard** [comment]
Hi Jeremy,

Thank for the info.

You can have a look to the public documentation of our IoT platform - event
processing section :
https://liveobjects.orange-business.com/doc/html/lo_manual.html#SEP

Best regards,
Aurelien


2017-06-30 17:39 GMT+02:00 Jeremy Wadhams <notifications@github.com>:
