### ISSUE TITLE
'average' operator for array

### ISSUE THREAD

**Issue by virajkanwade** [jwadhams/json-logic-js#62]
It would be nice to have an ability to write a rule like 'if the average of <given> values is > 15'

**Comment by lucas2595** [comment]
Well... you can always do something like:
```
{
	"/": [{
		"reduce": [{
				"var": "integers"
			},
			{
				"+": [{
					"var": "current"
				}, {
					"var": "accumulator"
				}]
			},
			0
		]
	}, {
		"reduce": [{
				"map": [{
					"var": "integers"
				}, {
					"if": [{
						"var": ""
					}, 1, 0]
				}]
			},
			{
				"+": [{
					"var": "current"
				}, {
					"var": "accumulator"
				}]
			},
			0
		]
	}]
}
```
Here the data is `{"integers":[1,2,10,10]}`

The first `reduce` calculates the sum of the elements of the array, and the second calculates the array's length (got from https://github.com/jwadhams/json-logic/issues/4#issuecomment-402053990)

**Comment by jwadhams** [comment]
This would be straightforward to add as a custom operator, like

```js
jsonLogic.add_operation('average', (...args) => {
  if (!args || !args.length) return 0;
  let sum = args.reduce((accumulator, item) => accumulator+item, 0);
  return sum / args.length;
});

jsonLogic.apply({'average':[2,4,6]}); // returns 4
```

Since this isn't a language built-in in JavaScript, I'm a little hesitant to make it one in json-logic -- especially because letting users roll their own lets you decide how you want to handle zero-length arrays, non-numeric items, etc etc etc.
