### ISSUE TITLE
⚠️ This library is insecure and can lead to Remote Code Execution ⚠️

### ISSUE THREAD

**Issue by arel** [jwadhams/json-logic-js#86]
Be aware that this library appears unmaintained and has an unpatched vulnerability that makes it **unsafe to use in production**.

https://npmjs.com/advisories/1542

**Comment by jwadhams** [comment]
@arel I just published version 2.0.0 which removes the `method` operation. What are my next steps to get this version evaluated and (hopefully) cleared in the advisory? 

The brand new version is still listed in the "affected" tab, but I don't know if that's because I'm failing some unit test, or if the advisory just has a too-broad semver rule. https://www.npmjs.com/advisories/1542/versions

**Comment by jwadhams** [comment]
If you allow untrusted users to submit JsonLogic **rules** please update to 2.0.0 (or later) at your earliest convenience, to remediate this issue.  2.0.0 has been confirmed to no longer be subject to this advisory.

(I chose a major version bump because it is removing functionality, even if it's uncommonly used)

https://www.npmjs.com/advisories/1542/versions

**Comment by arel** [comment]
@jwadhams Thanks for updating the library! In addition to removing the `method` operation, the other things I would recommend are (I don't remember if you're doing these already):

* blacklist `__proto__` as a variable name and/or restrict the set of valid variable/function names (e.g., to start match `^[a-zA-Z][a-zA-Z0-9]*$`)
* use `hasOwnProperty()` before looking up any variables or function names, recursively if necessary, to prevent access to an object's prototype's properties.

    ```javascript
    let data;

    data = {};
    data.hasOwnProperty("toString");  // false
    data["toString"];  // ƒ toString() { [native code] }

    data = { toString: {abc: 'xyz'} };
    data.hasOwnProperty("toString");  // true
    data["toString"];  // {abc: "xyz"}

    data["toString"]["toString"];  // ƒ toString() { [native code] }
    ```
