### ISSUE TITLE
Unclear error 

### ISSUE THREAD

**Issue by DavidC0V** [jwadhams/json-logic-js#92]
Minimum reproduction:
```
const jsonLogic = require("json-logic-js");
jsonLogic.add_operation("split", String.prototype.split.call);
jsonLogic.apply({"split": ["file.json", "."]});
```
Expected:
```
Unrecognized operation split 
```

Actual:
```
operations[op].apply is not a function 
```

Unclear which operation is the cause of the error (from this default message)

**Comment by jwadhams** [comment]
I think there are some weird shenanigans happening inside JavaScript here. 

When you define a new operation, we add it to the private `operations` array then call it, assuming it's a function with an `apply()` method in logic.js on line 344 like:
```js
      return operations[op].apply(data, values);
```

So the exception you're seeing literally means `operations['split']` (which you successfully defined) does not have an apply method--because in normal operation you'd never chain `.call.apply`

```js
> typeof String.prototype.split.call.apply
'function'
> String.prototype.split.call.apply({}, ['thing.json', '.']);
Thrown:
TypeError: String.prototype.split.call.apply is not a function
```

So my suggestion would be to wrap the operation in a little function that clarifies how the args are used, maybe something like

```js
const jsonLogic = require("./logic.js");
jsonLogic.add_operation("split", (string, separator, limit) => String.prototype.split.apply(string, [separator, limit]));
jsonLogic.apply({"split": ["file.json", "."]});
// returns [ 'file', 'json' ]
```
